<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Checkers')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?=
                $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?=
                $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
                ->prependStylesheet($this->basePath('css/style.css'))
                ->prependStylesheet('https://newcss.net/theme/night.css')
                ->prependStylesheet('https://cdn.jsdelivr.net/npm/@exampledev/new.css@1.1.2/new.min.css')
                ->prependStylesheet('https://fonts.xz.style/serve/inter.css')
        ?>

        <!-- Scripts -->
        <?= $this->headScript() ?>
    </head>
    <body>
        <div style="flex-direction: row; height: 100vh;">
            <div class="left-side">
                <p>Checkers game</p>
                <a style="margin-left: -3px;" href="<?= $this->url('application', [ 'action' => 'new']) ?>"><button>New game</button></a>
                <div style="flex: 1;"></div>
                <p>Made with s2 by <a href="https://renanliberato.com.br">Renan Liberato</a></p>
                <p>Check the <a href="https://github.com/renanliberato/checkers">source code</a></p>
            </div>
            <div class="container">
                <?= $this->content ?>
            </div>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
