<div id="board" style="box-shadow: inset 0 0 3px #000000; width: 620px; padding: 10px;">
    <?php foreach ($board->spaces as $rowKey => $row): ?>
        <div style="display: flex;">
            <?php foreach ($row as $columnKey => $space): ?>
                <div data-row='<?= $rowKey ?>' data-column='<?= $columnKey ?>' id='space<?= $rowKey ?><?= $columnKey ?>' style="position: relative; width: 60px; height: 60px; background-color: <?= $space->color == 'black' ? '#222222' : '#eeeeee' ?>" <?= $space->color == 'black' ? 'ondrop="drop(event)" ondragover="allowDrop(event)"' : '' ?>>
                    <?php if ($space->checker != null): ?>
                        <div id='checker<?= $space->checker->id ?>' <?= $space->checker->team == $userTeam ? 'draggable="true"' : '' ?> ondragstart="drag(event)" style="position: absolute; top: 10px; left: 10px; right: 10px; bottom: 10px; width: 40px; height: 40px; border-radius: 20px; background-color: <?= $space->checker->color ?>; box-shadow: inset 0 0 3px #000000; <?= $space->checker->team == $userTeam ? 'cursor: pointer' : '' ?>"></div>
                    <?php endif; ?>
                </div>
            <?php endforeach; ?>
        </div>
    <?php endforeach; ?>
</div>