<?php

function positionToClass($row, $column) {
    return ($row + $column) % 2 == 0 ? 'black' : 'white';
}

$boardDefinition = [
    [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
    [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
    [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
    [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
    [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
    [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
    [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
    [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
    [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
    [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
];
$posCounter = 1;
?>
<div style="flex-direction: row; flex: 1;">
    <div id="board">
        <div class="player-bar <?= $turn == 'b' ? 'turn-to-play' : '' ?>">
            <img src="/checkers/img/user.jfif"/>
            <div>
                <p>Opponent</p>
            </div>
        </div>
        <div id="board-inner">
            <div id='disable-movement' style='display: none;'></div>
            <?php if ($result !== null): ?>
                <div class="result-container">
                    <div class='result'>
                        <?php if ($result == 'win'): ?>
                            <span>YOU WIN!</span>
                        <?php else: ?>
                            <span>YOU LOSE!</span>
                        <?php endif; ?>
                        <a style='margin-top: 10px;' href="/checkers/application/index/new"><button style='padding: 10px 20px;'>Play again!</button></a>
                    </div>
                </div>
            <?php endif; ?>
            <div style="z-index: 999; position: absolute; bottom: 0; left: 0; right: 0; flex-direction: row; justify-content: space-around;">
                <?php foreach (['j', 'i', 'h', 'g', 'f', 'e', 'd', 'c', 'b', 'a'] as $columnKey): ?>
                    <span class="column-label"><?= $columnKey ?></span>
                <?php endforeach; ?>
            </div>
            <?php foreach ($boardDefinition as $rowKey => $row): ?>
                <div style="flex-direction: row; position: relative;">
                    <span class="row-label"><?= $rowKey + 1 ?></span>
                    <?php foreach ($row as $type): ?>
                        <?php if ($type == 0): ?>
                            <div class="space black" data-position='<?= $posCounter ?>' ondrop="drop(event)" ondragover="allowDrop(event)">
                                <?=
                                $this->partial('partials/checker.phtml', [
                                    'possibleMoves' => $possibleMoves,
                                    'checkers' => $checkers,
                                    'position' => $posCounter++,
                                ])
                                ?>
                            </div>
                        <?php else: ?>
                            <div class="space white"></div>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </div>
            <?php endforeach; ?>
        </div>
        <div class="player-bar <?= $turn == 'w' ? 'turn-to-play' : '' ?>">
            <img src="/checkers/img/user.jfif"/>
            <div>
                <p>You</p>
            </div>
        </div>
    </div>
    <div style="flex: 1; margin-left: 10px; background: var(--nc-bg-4); padding: 10px; height: calc(100vh - 40px); overflow-y: auto;">
        <ol>
            <?php foreach ($movements as $movement): ?>
                <li>
                    <div style="font-size: 13px; color: #AEADA5; font-weight: bold; display: inline-block; width: 75px;"><?= $movement['from'] . ' - ' . $movement['to'] ?></div>
                    <div style="font-size: 13px; color: #AEADA5; font-weight: bold; display: inline-block;width: 75px;"><?= $movement['from'] . ' - ' . $movement['to'] ?></div>
                </li>
            <?php endforeach; ?>
        </ol>
    </div>
</div>