<?php
$checker = isset($checkers[$position]) ? $checkers[$position] : null;
$canMove = array_search($position, $possibleMoves) !== false;
?>

<?php if ($checker): ?>
    <div
        data-canmoveto='[]'
        data-position='<?= $checker->position ?>'
        id='checker<?= $checker->position ?>'
        <?= $canMove ? 'draggable="true" ondragstart="drag(event)" ' : '' ?>
        class='checker <?= $canMove ? 'movable' : '' ?> <?= $checker->color ?>'></div>
<?php endif; ?>
